server:
  port: 8877
camel:
  springboot:
    auto-startup: true

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    jdbcUrl: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

